spring:
  application:
    name: project

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  token:
    access_expiration_time: 86400000 # ??
    refresh_expiration_time: 604800000 # 7?

logging:
  file:
    name: /home/ec2-user/output.log
    max-size: 10MB
    max-history: 30


